### ISSUE TITLE
Investigate collaborative workspace solution

### ISSUE THREAD

**Issue by ayoungethan** [openfoodsource/OFS_federation#23]
https://wordpress.org/plugins/buddypress-docs/ might allow in-site collaboration between OFS.org site users

@guising mentioned potential issues with the buddypress plugin, which would rule out buddypress-docs immediately.  There may be other reasons not to use it, either (i will investigate those)

**Comment by ayoungethan** [comment]
It does look like buddypress-docs will meet our needs: https://wordpress.org/plugins/buddypress-docs/

Google Docs could serve as the workspace if we don't find a suitable open source solution

**Comment by guising** [comment]
Some thoughts on buddypress: Note that I initially installed the buddypress module and then chose to disable that installation -- maybe just because it didn't offer page access restrictions like groups does, which is what was needed at the time.

I like to weigh how much complexity a module adds vs how much its utility it provides. So I have nothing specifically against buddypress. It seems like a good package for a site that stands alone and needs the ability for members to interact. On the other hand, OFS has github, a facebook page, a google plus page, and google documents (if needed). I think buddypress is more about sites that are facebook wanna-be sites, which isn't really OFS's intention.

Groups offers "permission" to access certain pages and other media based upon group membership. In the immediate case, this is needed to restrict access for download for "registered" users. In later cases, I can imagine certain pages with sensitive content being restricted to developers or federation members of various types. Buddypress seems more about "sharing" than "restricting", which is fine, but maybe not necessary.

If we need a specific buddypress feature, we can certainly look at it again.

**Comment by ayoungethan** [comment]
I wonder if the forums are enough, or if we should scrap the forums and just use BuddyPress only?

**Comment by ayoungethan** [comment]
(from email)
We are considering using BuddyPress for the OFS.org website as a more robust tool for collaboration between Federation members and other OFS users for developing documentation [how-to's, FAQs, best practices, etc], providing community-based support, articles for the OFS.org website/newsletter, etc.  Although I think it needs further investigation, my sense is that maybe BuddyPress is not so overkill for such a purpose, although it seems overkill for local foodhubs.  That said, I will gladly stick with a more atomized solution including the existing forums plugin, if we can figure out a solution to the "collaborative community workspace" question for the co-development of content.  It needs to be _non-technical (e.g., WYSIWYG), so no wiki markup stuff._  Like Google Docs, but not Google.

**Comment by guising** [comment]
I have never used BuddyPress, but here are some additional considerations. BuddyPress does seem to enable its own version of forums and groups, however I am not sure how well it plays with the [non-BuddyPress] Groups plugin. When I initially tried BuddyPress, I don't think it provided the access permission I was looking for, which the Groups plugin does provide. However, it is possible that Groups is not needed on the OFS site itself, and maybe BuddyPress would fill that need.

However, I still have these concerns: BuddyPress is (apparently) great for social networking: sharing comments with friends, sending personal messages, and that sort of thing. I quesion how much we need (or want to encourage) that sort of activity in a collaborative environment. OFS should not be organized as a "club" with an infrastructure that encourages membrs to form cliques. By _not_ using BuddyPress, it forces members to make their thoughts public promotes a general sharing of information. If folks want to share pictures of their kittens, OFS really isn't the place for that.

On the other hand, BuddyPress seems to be highly configurable and various pieces can be used without incorporating the whole, so if the forums work better and are more useable, that might be enough.

I'm not voting against BuddyPress (at least not now) but I want to wait to see if we really seem to need it. I think it will need to demonstrate a functionality or ease-of-use that we don't already have.

**Comment by ayoungethan** [comment]
it looks like buddypress + buddypress-docs and bbpress and a realtime chat function will provide what we need (there's even plugins that will provide webinar capacity)...see my post from #18 for the specifics. 

Last question:  Unsure whether Groups is redundant to BuddyPress functionality in all.
